# Generated by Django 4.2.4 on 2023-08-09 12:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('budgetmanager', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BudgetShare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('can_edit', models.BooleanField(default=False)),
                ('budget', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='budgetmanager.budget')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='budget',
            name='shared_users',
            field=models.ManyToManyField(blank=True, related_name='shared_budgets', through='budgetmanager.BudgetShare', to=settings.AUTH_USER_MODEL),
        ),
    ]
