# Generated by Django 4.2.4 on 2023-08-09 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgetmanager', '0002_budgetshare_budget_shared_users'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='budgetshare',
            constraint=models.UniqueConstraint(fields=('budget', 'user'), name='One budget membership per user per budget'),
        ),
    ]
