# Generated by Django 4.2.2 on 2023-07-18 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgetmanager', '0003_budget_user_payee_user_payment_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payee',
            name='active',
        ),
        migrations.AddField(
            model_name='payment',
            name='pending',
            field=models.BooleanField(default=False),
        ),
    ]
