# Generated by Django 4.2.2 on 2023-07-18 20:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('budgetmanager', '0004_remove_payee_active_payment_pending'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='description',
            new_name='notes',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='name',
        ),
    ]
