# Generated by Django 4.2.2 on 2023-07-20 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgetmanager', '0005_rename_description_payment_notes_remove_payment_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='pending',
            field=models.BooleanField(default=False, verbose_name='Exclude from total'),
        ),
    ]
